version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: ee_db
    restart: unless-stopped
    env_file: config/.env
    environment:
      POSTGRES_DB: epistemology_engine
      POSTGRES_USER: ${PGUSER:-user}
      POSTGRES_PASSWORD: ${PGPASSWORD:-password}
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-user} -d ${PGDATABASE:-epistemology_engine}"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
